# Generated by Selenium IDE
# import pytest

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestLoginPage():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.driver.get("https://www.saucedemo.com/")
        self.driver.set_window_size(1296, 768)
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    # Méthodes helper
    def trouver_element_cliquable(self, selecteur):
            """Trouve et retourne un élément cliquable"""
            return self.wait.until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, selecteur)))

    def trouver_element_visible(self, selecteur):
            """Trouve et retourne un élément visible"""
            return self.wait.until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, selecteur)))

    def test_login_avec_identifiants_valides(self):
        """
        Vérifie qu'un utilisateur standard peut se connecter avec des identifiants valides et accéder à la page des produits
        """

        username_field = self.wait.until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        username_field.click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("standard_user")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"title\"]").text == "Products"


    def test_login_avec_utilisateurbloquer(self):
        """
    Vérifie qu'un utilisateur bloquer ne peut pas se connecter et accéder à la page des produits
        """

        username_field = self.wait.until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, "*[data-test=\"username\"]")))
        username_field.click()
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"username\"]").send_keys("locked_out_user")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"password\"]").send_keys("secret_sauce")
        self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"login-button\"]").click()
        assert self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"error\"]").text == "Epic sadface: Sorry, this user has been locked out."
